#!/usr/bin/env zsh

# Make vim the default editor.
export EDITOR='vim';

# Enable persistent REPL history for `node`.:
export NODE_REPL_HISTORY=~/.node_history;

# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';

# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";

# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Misc
export MANPAGER='less -X'
export CHEATCOLORS=true
export GOPATH="$HOME/bin"

export PERL5BASE="$HOME/perl5"
export PERL5LIB="$PERL5LIB:$PERL5BASE/lib/perl5"
export PERLDB_OPTS="LineInfo=perldb.out"
export PERL_LOCAL_LIB_ROOT="$PERL_LOCAL_LIB_ROOT:$PERL5BASE"
export PERL_MM_OPT="INSTALL_BASE=$PERL5BASE"
export PERL_MB_OPT="--install_base $PERL5BASE"

#export BROWSER=/usr/bin/brave
