#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--add', dest='track', metavar='PATH', help='Track a new file')
parser.add_argument('--tracked', action='store_true', help='List tracked files')
parser.add_argument('--remove', dest='untrack', metavar='PATH', help='Untrack a tracked file')
parser.add_argument('--untracked', action='store_true', help='List untracked files')

args = parser.parse_args()

def dotctl():
    print(args)

if __name__ == "__main__":
    dotctl()    